// Summarize and impromptu format prompt data

import type { LibraryPrompt } from './promptLibrary.types';

export const SUMMARIZE_FORMAT_PROMPTS = [
  // ── Summarize format (6) ──────────────────────────────────────────
  {
    id: 'sum-climate-report',
    category: 'Academic',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'summarize',
    title: 'Climate action report',
    hint: 'Read the text, then deliver a concise spoken summary',
    text: 'Read the following text about climate action, then summarise the key points in a spoken summary.',
    sourceText:
      'The latest report from the Intergovernmental Panel on Climate Change warns that global temperatures are on track to exceed 1.5 degrees Celsius above pre-industrial levels by the early 2030s. The report identifies fossil fuel use, deforestation, and industrial agriculture as the primary drivers. However, it also highlights that renewable energy costs have dropped by over 80 percent in the past decade, making a rapid transition technically feasible. The authors recommend immediate action in three areas: phasing out coal power by 2035, protecting and restoring forests, and shifting subsidies from fossil fuels to clean energy. Critics argue that these targets are unrealistic without massive investment in developing nations, where energy demand is growing fastest. The report concludes that the window for limiting warming is narrow but still open.',
  },
  {
    id: 'sum-remote-learning',
    category: 'Academic',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'summarize',
    title: 'Remote learning outcomes',
    hint: 'Identify the main findings and present them clearly',
    text: 'Read the following text about remote learning, then summarise the main findings in a spoken summary.',
    sourceText:
      'A multi-university study published in 2025 tracked 12,000 students across three years to compare outcomes between in-person and remote learners. The results were mixed. Students in remote programmes reported higher satisfaction with schedule flexibility and saved an average of eight hours per week on commuting. However, completion rates for remote students were 15 percent lower than for in-person peers. The gap was largest among first-year students, who appeared to benefit most from face-to-face interaction with instructors and classmates. Interestingly, remote students in STEM fields performed nearly as well as their in-person counterparts, possibly because online labs and simulations were well-developed. The researchers recommended a hybrid model as the optimal compromise, combining the social benefits of campus attendance with the flexibility of remote access.',
  },
  {
    id: 'sum-ai-workforce',
    category: 'Professional',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'summarize',
    title: 'AI and the workforce',
    hint: 'Capture the nuance — both risks and opportunities',
    text: 'Read the following text about AI in the workforce, then deliver a balanced spoken summary.',
    sourceText:
      'A 2025 report from the World Economic Forum estimates that artificial intelligence will displace 85 million jobs globally by 2030 but create 97 million new ones. The net gain of 12 million jobs masks significant disruption: roles in data entry, basic accounting, and customer service call centres face the highest risk. Meanwhile, demand is surging for AI trainers, prompt engineers, ethics auditors, and human-machine collaboration specialists. The report emphasises that the transition will not be smooth. Workers over 50 and those without tertiary education face the steepest re-skilling curve. Governments that invest in lifelong learning programmes and portable benefits will fare better. The authors warn that without policy intervention, AI could widen inequality even as it boosts overall productivity.',
  },
  {
    id: 'sum-urban-farming',
    category: 'Daily',
    cefrLevel: 'B2',
    duration: '90s',
    format: 'summarize',
    title: 'Urban farming movement',
    hint: 'Summarise the trend, the benefits, and the challenges',
    text: 'Read the following text about urban farming, then summarise the trend in a spoken summary.',
    sourceText:
      'Urban farming has grown from a niche hobby into a serious food production strategy. Cities like Singapore, Detroit, and Paris now host vertical farms that produce leafy greens year-round using 95 percent less water than traditional agriculture. Advocates say urban farms reduce food miles, create local jobs, and turn abandoned lots into productive spaces. Community gardens have also expanded, with waiting lists in many European cities exceeding two years. However, critics point out that urban farms remain expensive to build and operate, and they cannot produce staple crops like wheat or rice at scale. Most urban farms focus on high-value greens and herbs, leaving the bulk of food production to rural agriculture. The question is whether technology can close this gap.',
  },
  {
    id: 'sum-digital-privacy',
    category: 'Social',
    cefrLevel: 'C2',
    duration: '180s',
    format: 'summarize',
    title: 'Digital privacy landscape',
    hint: 'Summarise the competing perspectives and regulatory trends',
    text: 'Read the following text about digital privacy, then summarise the competing perspectives in a spoken summary.',
    sourceText:
      'The digital privacy landscape has shifted dramatically since the European Union enacted the General Data Protection Regulation in 2018. Over 140 countries now have some form of data protection law, yet enforcement varies wildly. In the United States, a patchwork of state-level laws has created confusion for businesses operating nationally. Meanwhile, tech companies argue that strict privacy rules stifle innovation and make personalised services impossible. Privacy advocates counter that users rarely understand what they consent to — studies show fewer than 5 percent of people read terms of service. A growing movement advocates for "privacy by design," where systems are built from the ground up to minimise data collection. Some researchers propose a radical alternative: treating personal data as property that individuals can license, creating a marketplace where users are compensated for sharing their information.',
  },
  {
    id: 'sum-space-economy',
    category: 'Academic',
    cefrLevel: 'C2',
    duration: '180s',
    format: 'summarize',
    title: 'The emerging space economy',
    hint: 'Summarise the economic forces and geopolitical tensions',
    text: 'Read the following text about the space economy, then summarise the key developments in a spoken summary.',
    sourceText:
      'The global space economy surpassed $600 billion in 2025, driven primarily by satellite communications and Earth observation services. Private companies now launch more rockets annually than government agencies, and the cost per kilogram to low Earth orbit has fallen from $54,000 in 2010 to under $2,700. This cost reduction has enabled new industries: satellite internet constellations serve remote communities, precision agriculture relies on orbital imaging, and insurance companies use space-based data to assess climate risk. However, the rapid commercialisation of space has raised governance concerns. The 1967 Outer Space Treaty, drafted during the Cold War, does not address resource extraction or orbital pollution from defunct satellites. With over 10,000 active satellites and growing, the risk of cascading collisions — the so-called Kessler syndrome — could render certain orbits unusable within decades. Nations are negotiating new frameworks, but progress is slow.',
  },
] as const satisfies readonly LibraryPrompt[];

export const IMPROMPTU_FORMAT_PROMPTS = [
  // ── Impromptu format (10) ─────────────────────────────────────────
  {
    id: 'improv-unexpected-news',
    category: 'Daily',
    cefrLevel: 'B1',
    duration: '60s',
    format: 'impromptu',
    title: 'Unexpected news',
    hint: 'You have 30 seconds to prepare, then speak',
    text: 'You just received unexpected good news. Describe the news and how you feel about it.',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-desert-island',
    category: 'Social',
    cefrLevel: 'B1',
    duration: '60s',
    format: 'impromptu',
    title: 'Desert island items',
    hint: 'Choose three items and justify each one',
    text: 'If you were stranded on a desert island, what three items would you bring and why?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-time-travel',
    category: 'Social',
    cefrLevel: 'B2',
    duration: '90s',
    format: 'impromptu',
    title: 'Time travel destination',
    hint: 'Pick a time period and explain your choice',
    text: 'If you could travel to any period in history, when and where would you go? What would you do there?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-new-law',
    category: 'Academic',
    cefrLevel: 'B2',
    duration: '90s',
    format: 'impromptu',
    title: 'Propose a new law',
    hint: 'State the law, the problem it solves, and possible objections',
    text: 'If you could create one new law for your country, what would it be and why?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-mentor-dinner',
    category: 'Professional',
    cefrLevel: 'B2',
    duration: '90s',
    format: 'impromptu',
    title: 'Dinner with a mentor',
    hint: 'Who would you choose and what would you ask?',
    text: 'If you could have dinner with any professional mentor, living or dead, who would it be and what would you discuss?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-career-switch',
    category: 'Professional',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'impromptu',
    title: 'Career switch',
    hint: 'Explain the change and how you would prepare',
    text: 'If you had to switch careers tomorrow, what field would you move into and how would you prepare?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-future-city',
    category: 'Academic',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'impromptu',
    title: 'City of the future',
    hint: 'Describe what daily life would look like',
    text: 'Describe what a city might look like in the year 2100. Focus on daily life, transport, and community.',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-unpopular-opinion',
    category: 'Social',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'impromptu',
    title: 'Defend an unpopular opinion',
    hint: 'Take a contrarian stance and argue it well',
    text: 'Share an unpopular opinion you hold and defend it with clear reasoning.',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-ethical-dilemma',
    category: 'Academic',
    cefrLevel: 'C2',
    duration: '180s',
    format: 'impromptu',
    title: 'Ethical dilemma',
    hint: 'Explore both sides before stating your position',
    text: 'A self-driving car must choose between protecting its passenger or a pedestrian. What should it do, and who should decide?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-rewrite-history',
    category: 'Academic',
    cefrLevel: 'C2',
    duration: '180s',
    format: 'impromptu',
    title: 'Rewrite one historical event',
    hint: 'Choose an event, change the outcome, and trace the consequences',
    text: 'If you could change the outcome of one historical event, which would it be and what ripple effects do you think it would have?',
    prepTimeSecs: 30,
  },
] as const satisfies readonly LibraryPrompt[];
