// Curated prompt library for the /prompts browsable grid — richer display type than prompts.config

import type { LibraryCategory, LibraryPrompt } from './promptLibrary.types';

export const LIBRARY_CATEGORIES: readonly LibraryCategory[] = [
  'Professional',
  'Social',
  'Academic',
  'Daily',
] as const;

export const PROMPT_LIBRARY = [
  // ── Professional (7) ──────────────────────────────────────────────
  {
    id: 'pro-intro',
    category: 'Professional',
    cefrLevel: 'B1',
    duration: '90s',
    title: 'Tell me about yourself',
    hint: 'Classic job interview opener',
    text: 'Tell me about yourself and your professional background.',
  },
  {
    id: 'pro-challenge',
    category: 'Professional',
    cefrLevel: 'B2',
    duration: '120s',
    title: 'A challenging project',
    hint: 'Describe a project and what you learned',
    text: 'Describe a challenging project you worked on and what you learned from it.',
  },
  {
    id: 'pro-five-year',
    category: 'Professional',
    cefrLevel: 'B1',
    duration: '90s',
    title: 'Five-year vision',
    hint: 'Where do you see yourself professionally?',
    text: 'Where do you see yourself professionally in five years?',
  },
  {
    id: 'pro-strengths',
    category: 'Professional',
    cefrLevel: 'B2',
    duration: '120s',
    title: 'Strengths and weaknesses',
    hint: 'Honest reflection on your professional traits',
    text: 'What are your greatest professional strengths, and how do you manage your main weakness?',
  },
  {
    id: 'pro-conflict',
    category: 'Professional',
    cefrLevel: 'C1',
    duration: '120s',
    title: 'Resolving a disagreement',
    hint: 'Navigating workplace conflict diplomatically',
    text: 'Describe a time you disagreed with a colleague and how you resolved it.',
  },
  {
    id: 'pro-presentation',
    category: 'Professional',
    cefrLevel: 'B2',
    duration: '120s',
    title: 'Present an idea',
    hint: 'Pitch a product, process, or improvement',
    text: 'Imagine you have two minutes to pitch a new idea to your team. Go ahead.',
  },
  {
    id: 'pro-meeting',
    category: 'Professional',
    cefrLevel: 'B1',
    duration: '60s',
    title: 'Catch me up',
    hint: 'Summarise a project status clearly',
    text: 'You just joined a call late. Summarise where your current project stands in under a minute.',
  },

  // ── Social (7) ────────────────────────────────────────────────────
  {
    id: 'soc-small-talk',
    category: 'Social',
    cefrLevel: 'A2',
    duration: '60s',
    title: 'Weekend small talk',
    hint: 'Light and natural everyday conversation',
    text: 'Tell me about your weekend — what did you do and what did you enjoy most?',
  },
  {
    id: 'soc-recommend',
    category: 'Social',
    cefrLevel: 'B1',
    duration: '60s',
    title: 'Recommend something',
    hint: 'A film, book, place, or restaurant you loved',
    text: 'Recommend something you discovered recently — a film, a book, a restaurant, or a place — and explain why.',
  },
  {
    id: 'soc-story',
    category: 'Social',
    cefrLevel: 'B1',
    duration: '90s',
    title: 'A funny story',
    hint: 'Recount something that made you laugh',
    text: 'Tell me a funny or surprising story that happened to you.',
  },
  {
    id: 'soc-opinion',
    category: 'Social',
    cefrLevel: 'B2',
    duration: '90s',
    title: 'Share your opinion',
    hint: 'Agree or disagree on an everyday topic',
    text: 'Do you think social media has improved or worsened the way people communicate? Share your view.',
  },
  {
    id: 'soc-intro-friend',
    category: 'Social',
    cefrLevel: 'A2',
    duration: '30s',
    title: 'Introduce a friend',
    hint: 'Practice warm, clear introductions',
    text: 'Imagine you are introducing your best friend to someone new. Describe them in 30 seconds.',
  },
  {
    id: 'soc-debate',
    category: 'Social',
    cefrLevel: 'B2',
    duration: '90s',
    title: 'Mini debate',
    hint: 'Argue one side of a common disagreement',
    text: 'Is it better to work for a startup or a big company? Argue your position.',
  },
  {
    id: 'soc-travel-tip',
    category: 'Social',
    cefrLevel: 'B1',
    duration: '60s',
    title: 'Travel tip',
    hint: 'Share a useful travel insight',
    text: 'Share one piece of advice you would give someone visiting your country or city for the first time.',
  },

  // ── Academic (7) ──────────────────────────────────────────────────
  {
    id: 'acad-correlation',
    category: 'Academic',
    cefrLevel: 'B1',
    duration: '90s',
    title: 'Correlation vs. causation',
    hint: 'Explain with a real-world example',
    text: 'Explain the difference between correlation and causation with an example.',
  },
  {
    id: 'acad-tech-trend',
    category: 'Academic',
    cefrLevel: 'B2',
    duration: '120s',
    title: 'A technology trend',
    hint: 'Speculate on the near future',
    text: 'Describe a technology trend you think will be significant in the next decade.',
  },
  {
    id: 'acad-remote-work',
    category: 'Academic',
    cefrLevel: 'B2',
    duration: '120s',
    title: 'Remote work debate',
    hint: 'For or against, with evidence',
    text: 'Argue for or against remote work as the default mode for software teams.',
  },
  {
    id: 'acad-climate',
    category: 'Academic',
    cefrLevel: 'C1',
    duration: '120s',
    title: 'Climate policy',
    hint: 'Explain trade-offs of one policy',
    text: 'Summarise one climate policy you support and the trade-offs it involves.',
  },
  {
    id: 'acad-ai-ethics',
    category: 'Academic',
    cefrLevel: 'C1',
    duration: '120s',
    title: 'AI ethics',
    hint: 'What concerns you most about AI?',
    text: 'What ethical concern about AI in education worries you most, and why?',
  },
  {
    id: 'acad-concept',
    category: 'Academic',
    cefrLevel: 'B1',
    duration: '90s',
    title: 'Explain a concept',
    hint: 'Teach it simply to a non-expert',
    text: 'Choose a concept from your field and explain it as if the listener has no background in it.',
  },
  {
    id: 'acad-argument',
    category: 'Academic',
    cefrLevel: 'B2',
    duration: '120s',
    title: 'Build an argument',
    hint: 'Present a clear thesis with support',
    text: 'Pick any topic you care about and deliver a short structured argument: claim, evidence, conclusion.',
  },

  // ── Daily (7) ─────────────────────────────────────────────────────
  {
    id: 'daily-morning',
    category: 'Daily',
    cefrLevel: 'A2',
    duration: '60s',
    title: 'Morning routine',
    hint: 'Walk through your morning step by step',
    text: 'Describe what you did this morning from the moment you woke up.',
  },
  {
    id: 'daily-meal',
    category: 'Daily',
    cefrLevel: 'A2',
    duration: '60s',
    title: 'A memorable meal',
    hint: 'Talk about food you really enjoyed',
    text: 'Talk about a meal you really enjoyed recently and why it was memorable.',
  },
  {
    id: 'daily-evening',
    category: 'Daily',
    cefrLevel: 'B1',
    duration: '90s',
    title: 'Evening routine',
    hint: 'Step-by-step through your evening',
    text: 'What is your evening routine? Walk me through it step by step.',
  },
  {
    id: 'daily-weekend',
    category: 'Daily',
    cefrLevel: 'B1',
    duration: '90s',
    title: 'Typical vs. ideal weekend',
    hint: 'Compare what is vs. what you wish for',
    text: 'How do you usually spend your weekends? Compare a typical weekend to your ideal one.',
  },
  {
    id: 'daily-balance',
    category: 'Daily',
    cefrLevel: 'B2',
    duration: '120s',
    title: 'Work-life balance',
    hint: 'Reflect on how you split your time',
    text: 'How do you balance work, rest, and personal projects in a typical week?',
  },
  {
    id: 'daily-habit',
    category: 'Daily',
    cefrLevel: 'B1',
    duration: '60s',
    title: 'A habit you built',
    hint: 'Describe a good habit and how you formed it',
    text: 'Describe a positive habit you developed in the past year and how you built it.',
  },
  {
    id: 'daily-goal',
    category: 'Daily',
    cefrLevel: 'B2',
    duration: '90s',
    title: 'A goal you are working on',
    hint: 'Concrete, honest, detailed',
    text: 'Tell me about a personal or professional goal you are working toward right now.',
  },
] as const satisfies readonly LibraryPrompt[];

export function getLibraryByCategory(category: LibraryCategory): LibraryPrompt[] {
  return PROMPT_LIBRARY.filter((prompt) => prompt.category === category);
}

export function findPromptById(id: string): LibraryPrompt | null {
  return PROMPT_LIBRARY.find((prompt) => prompt.id === id) ?? null;
}
