// Curated prompt library for the /prompts browsable grid — richer display type than prompts.config

import type { CefrLevel, LibraryCategory, LibraryPrompt, PromptFormat } from './promptLibrary.types';
import { IMAGE_PROMPTS } from './imagePrompts';
import { RETELL_PASSAGES } from './retellPassages';

const imagePathMap = new Map(IMAGE_PROMPTS.map((p) => [p.id, p.imagePath]));
const retellTextMap = new Map(RETELL_PASSAGES.map((p) => [p.id, p.text]));

function getImagePath(id: string): string {
  const path = imagePathMap.get(id);
  if (path === undefined) throw new Error(`Missing image prompt: ${id}`);
  return path;
}

function getRetellText(id: string): string {
  const text = retellTextMap.get(id);
  if (text === undefined) throw new Error(`Missing retell passage: ${id}`);
  return text;
}

export const LIBRARY_CATEGORIES: readonly LibraryCategory[] = [
  'Professional',
  'Social',
  'Academic',
  'Daily',
] as const;

export const LIBRARY_FORMATS: readonly PromptFormat[] = [
  'opinion',
  'monologue',
  'image',
  'retell',
  'summarize',
  'impromptu',
] as const;

export const LIBRARY_CEFR_LEVELS: readonly CefrLevel[] = [
  'A2',
  'B1',
  'B2',
  'C1',
  'C2',
] as const;

export const PROMPT_LIBRARY = [
  // ── Professional (7) ──────────────────────────────────────────────
  {
    id: 'pro-intro',
    category: 'Professional',
    cefrLevel: 'B1',
    duration: '90s',
    format: 'monologue',
    title: 'Tell me about yourself',
    hint: 'Classic job interview opener',
    text: 'Tell me about yourself and your professional background.',
  },
  {
    id: 'pro-challenge',
    category: 'Professional',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'monologue',
    title: 'A challenging project',
    hint: 'Describe a project and what you learned',
    text: 'Describe a challenging project you worked on and what you learned from it.',
  },
  {
    id: 'pro-five-year',
    category: 'Professional',
    cefrLevel: 'B1',
    duration: '90s',
    format: 'monologue',
    title: 'Five-year vision',
    hint: 'Where do you see yourself professionally?',
    text: 'Where do you see yourself professionally in five years?',
  },
  {
    id: 'pro-strengths',
    category: 'Professional',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'monologue',
    title: 'Strengths and weaknesses',
    hint: 'Honest reflection on your professional traits',
    text: 'What are your greatest professional strengths, and how do you manage your main weakness?',
  },
  {
    id: 'pro-conflict',
    category: 'Professional',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'monologue',
    title: 'Resolving a disagreement',
    hint: 'Navigating workplace conflict diplomatically',
    text: 'Describe a time you disagreed with a colleague and how you resolved it.',
  },
  {
    id: 'pro-presentation',
    category: 'Professional',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'monologue',
    title: 'Present an idea',
    hint: 'Pitch a product, process, or improvement',
    text: 'Imagine you have two minutes to pitch a new idea to your team. Go ahead.',
  },
  {
    id: 'pro-meeting',
    category: 'Professional',
    cefrLevel: 'B1',
    duration: '60s',
    format: 'monologue',
    title: 'Catch me up',
    hint: 'Summarise a project status clearly',
    text: 'You just joined a call late. Summarise where your current project stands in under a minute.',
  },

  // ── Social (7) ────────────────────────────────────────────────────
  {
    id: 'soc-small-talk',
    category: 'Social',
    cefrLevel: 'A2',
    duration: '60s',
    format: 'monologue',
    title: 'Weekend small talk',
    hint: 'Light and natural everyday conversation',
    text: 'Tell me about your weekend — what did you do and what did you enjoy most?',
  },
  {
    id: 'soc-recommend',
    category: 'Social',
    cefrLevel: 'B1',
    duration: '60s',
    format: 'monologue',
    title: 'Recommend something',
    hint: 'A film, book, place, or restaurant you loved',
    text: 'Recommend something you discovered recently — a film, a book, a restaurant, or a place — and explain why.',
  },
  {
    id: 'soc-story',
    category: 'Social',
    cefrLevel: 'B1',
    duration: '90s',
    format: 'monologue',
    title: 'A funny story',
    hint: 'Recount something that made you laugh',
    text: 'Tell me a funny or surprising story that happened to you.',
  },
  {
    id: 'soc-opinion',
    category: 'Social',
    cefrLevel: 'B2',
    duration: '90s',
    format: 'opinion',
    title: 'Share your opinion',
    hint: 'Agree or disagree on an everyday topic',
    text: 'Do you think social media has improved or worsened the way people communicate? Share your view.',
  },
  {
    id: 'soc-intro-friend',
    category: 'Social',
    cefrLevel: 'A2',
    duration: '30s',
    format: 'monologue',
    title: 'Introduce a friend',
    hint: 'Practice warm, clear introductions',
    text: 'Imagine you are introducing your best friend to someone new. Describe them in 30 seconds.',
  },
  {
    id: 'soc-debate',
    category: 'Social',
    cefrLevel: 'B2',
    duration: '90s',
    format: 'opinion',
    title: 'Mini debate',
    hint: 'Argue one side of a common disagreement',
    text: 'Is it better to work for a startup or a big company? Argue your position.',
  },
  {
    id: 'soc-travel-tip',
    category: 'Social',
    cefrLevel: 'B1',
    duration: '60s',
    format: 'monologue',
    title: 'Travel tip',
    hint: 'Share a useful travel insight',
    text: 'Share one piece of advice you would give someone visiting your country or city for the first time.',
  },

  // ── Academic (7) ──────────────────────────────────────────────────
  {
    id: 'acad-correlation',
    category: 'Academic',
    cefrLevel: 'B1',
    duration: '90s',
    format: 'monologue',
    title: 'Correlation vs. causation',
    hint: 'Explain with a real-world example',
    text: 'Explain the difference between correlation and causation with an example.',
  },
  {
    id: 'acad-tech-trend',
    category: 'Academic',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'monologue',
    title: 'A technology trend',
    hint: 'Speculate on the near future',
    text: 'Describe a technology trend you think will be significant in the next decade.',
  },
  {
    id: 'acad-remote-work',
    category: 'Academic',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'opinion',
    title: 'Remote work debate',
    hint: 'For or against, with evidence',
    text: 'Argue for or against remote work as the default mode for software teams.',
  },
  {
    id: 'acad-climate',
    category: 'Academic',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'opinion',
    title: 'Climate policy',
    hint: 'Explain trade-offs of one policy',
    text: 'Summarise one climate policy you support and the trade-offs it involves.',
  },
  {
    id: 'acad-ai-ethics',
    category: 'Academic',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'opinion',
    title: 'AI ethics',
    hint: 'What concerns you most about AI?',
    text: 'What ethical concern about AI in education worries you most, and why?',
  },
  {
    id: 'acad-concept',
    category: 'Academic',
    cefrLevel: 'B1',
    duration: '90s',
    format: 'monologue',
    title: 'Explain a concept',
    hint: 'Teach it simply to a non-expert',
    text: 'Choose a concept from your field and explain it as if the listener has no background in it.',
  },
  {
    id: 'acad-argument',
    category: 'Academic',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'opinion',
    title: 'Build an argument',
    hint: 'Present a clear thesis with support',
    text: 'Pick any topic you care about and deliver a short structured argument: claim, evidence, conclusion.',
  },

  // ── Daily (7) ─────────────────────────────────────────────────────
  {
    id: 'daily-morning',
    category: 'Daily',
    cefrLevel: 'A2',
    duration: '60s',
    format: 'monologue',
    title: 'Morning routine',
    hint: 'Walk through your morning step by step',
    text: 'Describe what you did this morning from the moment you woke up.',
  },
  {
    id: 'daily-meal',
    category: 'Daily',
    cefrLevel: 'A2',
    duration: '60s',
    format: 'monologue',
    title: 'A memorable meal',
    hint: 'Talk about food you really enjoyed',
    text: 'Talk about a meal you really enjoyed recently and why it was memorable.',
  },
  {
    id: 'daily-evening',
    category: 'Daily',
    cefrLevel: 'B1',
    duration: '90s',
    format: 'monologue',
    title: 'Evening routine',
    hint: 'Step-by-step through your evening',
    text: 'What is your evening routine? Walk me through it step by step.',
  },
  {
    id: 'daily-weekend',
    category: 'Daily',
    cefrLevel: 'B1',
    duration: '90s',
    format: 'monologue',
    title: 'Typical vs. ideal weekend',
    hint: 'Compare what is vs. what you wish for',
    text: 'How do you usually spend your weekends? Compare a typical weekend to your ideal one.',
  },
  {
    id: 'daily-balance',
    category: 'Daily',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'opinion',
    title: 'Work-life balance',
    hint: 'Reflect on how you split your time',
    text: 'How do you balance work, rest, and personal projects in a typical week?',
  },
  {
    id: 'daily-habit',
    category: 'Daily',
    cefrLevel: 'B1',
    duration: '60s',
    format: 'monologue',
    title: 'A habit you built',
    hint: 'Describe a good habit and how you formed it',
    text: 'Describe a positive habit you developed in the past year and how you built it.',
  },
  {
    id: 'daily-goal',
    category: 'Daily',
    cefrLevel: 'B2',
    duration: '90s',
    format: 'monologue',
    title: 'A goal you are working on',
    hint: 'Concrete, honest, detailed',
    text: 'Tell me about a personal or professional goal you are working toward right now.',
  },

  // ── Image format (8) ──────────────────────────────────────────────
  {
    id: 'img-busy-market',
    category: 'Daily',
    cefrLevel: 'B1',
    duration: '120s',
    format: 'image',
    title: 'A busy city market',
    hint: 'Describe what you see and how it makes you feel',
    text: 'Look at this image of a busy city market. Describe the scene and say what visiting it would feel like.',
    imagePath: getImagePath('img-busy-market'),
  },
  {
    id: 'img-remote-office',
    category: 'Professional',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'image',
    title: 'Home office',
    hint: 'Describe the workspace and whether you would thrive there',
    text: 'Look at this home office setup. Describe the workspace and discuss whether you would be productive here.',
    imagePath: getImagePath('img-remote-office'),
  },
  {
    id: 'img-rush-hour',
    category: 'Daily',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'image',
    title: 'Rush hour commute',
    hint: 'Compare this scene to your own commuting experience',
    text: 'Look at this rush hour scene. Describe what you see and compare it to commuting in your city.',
    imagePath: getImagePath('img-rush-hour'),
  },
  {
    id: 'img-mountain-trail',
    category: 'Social',
    cefrLevel: 'B1',
    duration: '120s',
    format: 'image',
    title: 'Mountain trail at sunrise',
    hint: 'Describe the landscape and whether it appeals to you',
    text: 'Look at this mountain trail at sunrise. Describe the landscape and explain whether this kind of activity appeals to you.',
    imagePath: getImagePath('img-mountain-trail'),
  },
  {
    id: 'img-classroom',
    category: 'Academic',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'image',
    title: 'Modern classroom',
    hint: 'Compare this to your own educational experience',
    text: 'Look at this modern classroom. Describe the learning environment and compare it to your own educational experience.',
    imagePath: getImagePath('img-classroom'),
  },
  {
    id: 'img-elderly-park',
    category: 'Social',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'image',
    title: 'Couple in the park',
    hint: 'Reflect on ageing, community, and daily rituals',
    text: 'Look at this image of an elderly couple in a park. Describe the scene and reflect on what it says about ageing and community.',
    imagePath: getImagePath('img-elderly-park'),
  },
  {
    id: 'img-protest-march',
    category: 'Academic',
    cefrLevel: 'C2',
    duration: '180s',
    format: 'image',
    title: 'Peaceful protest',
    hint: 'Describe the event and discuss the role of public protest',
    text: 'Look at this protest march. Describe what is happening and discuss the role of public protest in a democracy.',
    imagePath: getImagePath('img-protest-march'),
  },
  {
    id: 'img-abandoned-factory',
    category: 'Academic',
    cefrLevel: 'C2',
    duration: '180s',
    format: 'image',
    title: 'Abandoned factory',
    hint: 'Speculate about economic change and what this place represents',
    text: 'Look at this abandoned factory. Describe the scene and speculate about its history and what it represents about economic change.',
    imagePath: getImagePath('img-abandoned-factory'),
  },

  // ── Retell format (8) ─────────────────────────────────────────────
  {
    id: 'retell-tech-revolution',
    category: 'Academic',
    cefrLevel: 'B1',
    duration: '90s',
    format: 'retell',
    title: 'The Quiet Tech Revolution',
    hint: 'Read the passage, then retell the key points in your own words',
    text: 'Read the passage about smartphone adoption, then retell the key points in your own words.',
    sourcePassage: getRetellText('retell-tech-revolution'),
  },
  {
    id: 'retell-ocean-plastic',
    category: 'Academic',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'retell',
    title: 'Ocean Plastic Crisis',
    hint: 'Retell the main argument and key facts',
    text: 'Read the passage about ocean plastic pollution, then retell the main argument and key facts.',
    sourcePassage: getRetellText('retell-ocean-plastic'),
  },
  {
    id: 'retell-solo-travel',
    category: 'Social',
    cefrLevel: 'B1',
    duration: '90s',
    format: 'retell',
    title: 'The Rise of Solo Travel',
    hint: 'Retell the reasons and advice mentioned in the passage',
    text: 'Read the passage about solo travel trends, then retell the reasons and advice mentioned.',
    sourcePassage: getRetellText('retell-solo-travel'),
  },
  {
    id: 'retell-sleep-science',
    category: 'Daily',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'retell',
    title: 'Why Sleep Matters',
    hint: 'Summarise the health evidence and workplace findings',
    text: 'Read the passage about sleep science, then retell the health evidence and workplace findings.',
    sourcePassage: getRetellText('retell-sleep-science'),
  },
  {
    id: 'retell-silk-road',
    category: 'Academic',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'retell',
    title: 'The Ancient Silk Road',
    hint: 'Retell the historical significance and modern parallels',
    text: 'Read the passage about the Silk Road, then retell its historical significance and modern parallels.',
    sourcePassage: getRetellText('retell-silk-road'),
  },
  {
    id: 'retell-street-food',
    category: 'Social',
    cefrLevel: 'B1',
    duration: '90s',
    format: 'retell',
    title: 'Street Food Culture',
    hint: 'Retell the examples and main message about street food',
    text: 'Read the passage about street food culture, then retell the examples and the main message.',
    sourcePassage: getRetellText('retell-street-food'),
  },
  {
    id: 'retell-quantum-basics',
    category: 'Academic',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'retell',
    title: 'Quantum Computing Explained',
    hint: 'Explain the key concepts as if teaching someone',
    text: 'Read the passage about quantum computing, then explain the key concepts as if teaching someone.',
    sourcePassage: getRetellText('retell-quantum-basics'),
  },
  {
    id: 'retell-gig-economy',
    category: 'Professional',
    cefrLevel: 'C2',
    duration: '180s',
    format: 'retell',
    title: 'The Gig Economy Debate',
    hint: 'Retell both sides of the argument and add your own view',
    text: 'Read the passage about the gig economy, then retell both sides of the argument and add your own view.',
    sourcePassage: getRetellText('retell-gig-economy'),
  },

  // ── Summarize format (6) ──────────────────────────────────────────
  {
    id: 'sum-climate-report',
    category: 'Academic',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'summarize',
    title: 'Climate action report',
    hint: 'Read the text, then deliver a concise spoken summary',
    text: 'Read the following text about climate action, then summarise the key points in a spoken summary.',
    sourceText: 'The latest report from the Intergovernmental Panel on Climate Change warns that global temperatures are on track to exceed 1.5 degrees Celsius above pre-industrial levels by the early 2030s. The report identifies fossil fuel use, deforestation, and industrial agriculture as the primary drivers. However, it also highlights that renewable energy costs have dropped by over 80 percent in the past decade, making a rapid transition technically feasible. The authors recommend immediate action in three areas: phasing out coal power by 2035, protecting and restoring forests, and shifting subsidies from fossil fuels to clean energy. Critics argue that these targets are unrealistic without massive investment in developing nations, where energy demand is growing fastest. The report concludes that the window for limiting warming is narrow but still open.',
  },
  {
    id: 'sum-remote-learning',
    category: 'Academic',
    cefrLevel: 'B2',
    duration: '120s',
    format: 'summarize',
    title: 'Remote learning outcomes',
    hint: 'Identify the main findings and present them clearly',
    text: 'Read the following text about remote learning, then summarise the main findings in a spoken summary.',
    sourceText: 'A multi-university study published in 2025 tracked 12,000 students across three years to compare outcomes between in-person and remote learners. The results were mixed. Students in remote programmes reported higher satisfaction with schedule flexibility and saved an average of eight hours per week on commuting. However, completion rates for remote students were 15 percent lower than for in-person peers. The gap was largest among first-year students, who appeared to benefit most from face-to-face interaction with instructors and classmates. Interestingly, remote students in STEM fields performed nearly as well as their in-person counterparts, possibly because online labs and simulations were well-developed. The researchers recommended a hybrid model as the optimal compromise, combining the social benefits of campus attendance with the flexibility of remote access.',
  },
  {
    id: 'sum-ai-workforce',
    category: 'Professional',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'summarize',
    title: 'AI and the workforce',
    hint: 'Capture the nuance — both risks and opportunities',
    text: 'Read the following text about AI in the workforce, then deliver a balanced spoken summary.',
    sourceText: 'A 2025 report from the World Economic Forum estimates that artificial intelligence will displace 85 million jobs globally by 2030 but create 97 million new ones. The net gain of 12 million jobs masks significant disruption: roles in data entry, basic accounting, and customer service call centres face the highest risk. Meanwhile, demand is surging for AI trainers, prompt engineers, ethics auditors, and human-machine collaboration specialists. The report emphasises that the transition will not be smooth. Workers over 50 and those without tertiary education face the steepest re-skilling curve. Governments that invest in lifelong learning programmes and portable benefits will fare better. The authors warn that without policy intervention, AI could widen inequality even as it boosts overall productivity.',
  },
  {
    id: 'sum-urban-farming',
    category: 'Daily',
    cefrLevel: 'B2',
    duration: '90s',
    format: 'summarize',
    title: 'Urban farming movement',
    hint: 'Summarise the trend, the benefits, and the challenges',
    text: 'Read the following text about urban farming, then summarise the trend in a spoken summary.',
    sourceText: 'Urban farming has grown from a niche hobby into a serious food production strategy. Cities like Singapore, Detroit, and Paris now host vertical farms that produce leafy greens year-round using 95 percent less water than traditional agriculture. Advocates say urban farms reduce food miles, create local jobs, and turn abandoned lots into productive spaces. Community gardens have also expanded, with waiting lists in many European cities exceeding two years. However, critics point out that urban farms remain expensive to build and operate, and they cannot produce staple crops like wheat or rice at scale. Most urban farms focus on high-value greens and herbs, leaving the bulk of food production to rural agriculture. The question is whether technology can close this gap.',
  },
  {
    id: 'sum-digital-privacy',
    category: 'Social',
    cefrLevel: 'C2',
    duration: '180s',
    format: 'summarize',
    title: 'Digital privacy landscape',
    hint: 'Summarise the competing perspectives and regulatory trends',
    text: 'Read the following text about digital privacy, then summarise the competing perspectives in a spoken summary.',
    sourceText: 'The digital privacy landscape has shifted dramatically since the European Union enacted the General Data Protection Regulation in 2018. Over 140 countries now have some form of data protection law, yet enforcement varies wildly. In the United States, a patchwork of state-level laws has created confusion for businesses operating nationally. Meanwhile, tech companies argue that strict privacy rules stifle innovation and make personalised services impossible. Privacy advocates counter that users rarely understand what they consent to — studies show fewer than 5 percent of people read terms of service. A growing movement advocates for "privacy by design," where systems are built from the ground up to minimise data collection. Some researchers propose a radical alternative: treating personal data as property that individuals can license, creating a marketplace where users are compensated for sharing their information.',
  },
  {
    id: 'sum-space-economy',
    category: 'Academic',
    cefrLevel: 'C2',
    duration: '180s',
    format: 'summarize',
    title: 'The emerging space economy',
    hint: 'Summarise the economic forces and geopolitical tensions',
    text: 'Read the following text about the space economy, then summarise the key developments in a spoken summary.',
    sourceText: 'The global space economy surpassed $600 billion in 2025, driven primarily by satellite communications and Earth observation services. Private companies now launch more rockets annually than government agencies, and the cost per kilogram to low Earth orbit has fallen from $54,000 in 2010 to under $2,700. This cost reduction has enabled new industries: satellite internet constellations serve remote communities, precision agriculture relies on orbital imaging, and insurance companies use space-based data to assess climate risk. However, the rapid commercialisation of space has raised governance concerns. The 1967 Outer Space Treaty, drafted during the Cold War, does not address resource extraction or orbital pollution from defunct satellites. With over 10,000 active satellites and growing, the risk of cascading collisions — known as Kessler syndrome — could render certain orbits unusable within decades. Nations are negotiating new frameworks, but progress is slow.',
  },

  // ── Impromptu format (10) ─────────────────────────────────────────
  {
    id: 'improv-unexpected-news',
    category: 'Daily',
    cefrLevel: 'B1',
    duration: '60s',
    format: 'impromptu',
    title: 'Unexpected news',
    hint: 'You have 30 seconds to prepare, then speak',
    text: 'You just received unexpected good news. Describe the news and how you feel about it.',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-desert-island',
    category: 'Social',
    cefrLevel: 'B1',
    duration: '60s',
    format: 'impromptu',
    title: 'Desert island items',
    hint: 'Choose three items and justify each one',
    text: 'If you were stranded on a desert island, what three items would you bring and why?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-time-travel',
    category: 'Social',
    cefrLevel: 'B2',
    duration: '90s',
    format: 'impromptu',
    title: 'Time travel destination',
    hint: 'Pick a time period and explain your choice',
    text: 'If you could travel to any period in history, when and where would you go? What would you do there?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-new-law',
    category: 'Academic',
    cefrLevel: 'B2',
    duration: '90s',
    format: 'impromptu',
    title: 'Propose a new law',
    hint: 'State the law, the problem it solves, and possible objections',
    text: 'If you could create one new law for your country, what would it be and why?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-mentor-dinner',
    category: 'Professional',
    cefrLevel: 'B2',
    duration: '90s',
    format: 'impromptu',
    title: 'Dinner with a mentor',
    hint: 'Who would you choose and what would you ask?',
    text: 'If you could have dinner with any professional mentor, living or dead, who would it be and what would you discuss?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-career-switch',
    category: 'Professional',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'impromptu',
    title: 'Career switch',
    hint: 'Explain the change and how you would prepare',
    text: 'If you had to switch careers tomorrow, what field would you move into and how would you prepare?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-future-city',
    category: 'Academic',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'impromptu',
    title: 'City of the future',
    hint: 'Describe what daily life would look like',
    text: 'Describe what a city might look like in the year 2100. Focus on daily life, transport, and community.',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-unpopular-opinion',
    category: 'Social',
    cefrLevel: 'C1',
    duration: '120s',
    format: 'impromptu',
    title: 'Defend an unpopular opinion',
    hint: 'Take a contrarian stance and argue it well',
    text: 'Share an unpopular opinion you hold and defend it with clear reasoning.',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-ethical-dilemma',
    category: 'Academic',
    cefrLevel: 'C2',
    duration: '180s',
    format: 'impromptu',
    title: 'Ethical dilemma',
    hint: 'Explore both sides before stating your position',
    text: 'A self-driving car must choose between protecting its passenger or a pedestrian. What should it do, and who should decide?',
    prepTimeSecs: 30,
  },
  {
    id: 'improv-rewrite-history',
    category: 'Academic',
    cefrLevel: 'C2',
    duration: '180s',
    format: 'impromptu',
    title: 'Rewrite one historical event',
    hint: 'Choose an event, change the outcome, and trace the consequences',
    text: 'If you could change the outcome of one historical event, which would it be and what ripple effects do you think it would have?',
    prepTimeSecs: 30,
  },
] as const satisfies readonly LibraryPrompt[];

// ── Helper functions ──────────────────────────────────────────────────

/** Returns all prompts in the library that belong to the given category. */
export function getLibraryByCategory(category: LibraryCategory): LibraryPrompt[] {
  return PROMPT_LIBRARY.filter((prompt) => prompt.category === category);
}

/** Finds a prompt by its unique ID, returning null if not found. */
export function findPromptById(id: string): LibraryPrompt | null {
  return PROMPT_LIBRARY.find((prompt) => prompt.id === id) ?? null;
}

/** Returns all prompts that match the given format (opinion, monologue, image, etc.). */
export function getLibraryByFormat(format: PromptFormat): LibraryPrompt[] {
  return PROMPT_LIBRARY.filter((prompt) => prompt.format === format);
}

/** Returns all prompts at the given CEFR level. */
export function getLibraryByCefrLevel(level: CefrLevel): LibraryPrompt[] {
  return PROMPT_LIBRARY.filter((prompt) => prompt.cefrLevel === level);
}
