// Static bridge rules mapping L1 interference tags to articulatory coaching data
import type { L1Tag } from './l1Spanish.types';
import type { BridgeRule } from './bridgeRules.types';

export const BRIDGE_RULES: Readonly<Record<L1Tag, BridgeRule>> = {
  // ── Consonant substitutions ──────────────────────────────────

  b_for_v: {
    tag: 'b_for_v',
    expected: 'v',
    spoken: 'b',
    severity: 'high',
    category: 'consonant',
    spanishAnchor: "You already know /b/ — lips pressed together",
    englishTarget: "English /v/ — top teeth touch your lower lip",
    bridgeInstruction: "Start from /b/ position, then lower your bottom lip so your top teeth rest on it. Let air flow continuously — don't pop the sound.",
    minimalPairs: [['very', 'berry'], ['vest', 'best'], ['van', 'ban'], ['vow', 'bow']],
    commonWords: ['very', 'have', 'give', 'over', 'every', 'move'],
  },

  th_substitution: {
    tag: 'th_substitution',
    expected: 'θ',
    spoken: 't',
    severity: 'high',
    category: 'consonant',
    spanishAnchor: "Spanish doesn't have /θ/ — you default to /t/ or /s/",
    englishTarget: "English /th/ as in 'think' — tongue tip between teeth",
    bridgeInstruction: "Place your tongue tip lightly between your upper and lower front teeth. Blow air out gently — it should feel breathy, not sharp like /t/.",
    minimalPairs: [['think', 'tink'], ['thin', 'tin'], ['three', 'tree'], ['bath', 'bat']],
    commonWords: ['think', 'three', 'thank', 'through', 'both', 'with'],
  },

  voiced_th_d: {
    tag: 'voiced_th_d',
    expected: 'ð',
    spoken: 'd',
    severity: 'high',
    category: 'consonant',
    spanishAnchor: "In Spanish, /d/ between vowels is close but not quite the same",
    englishTarget: "English /th/ as in 'this' — tongue between teeth with vibration",
    bridgeInstruction: "Same tongue position as 'think' (between teeth), but add voice. Feel your throat vibrate. It's softer than /d/.",
    minimalPairs: [['this', 'dis'], ['that', 'dat'], ['the', 'duh'], ['then', 'den']],
    commonWords: ['the', 'this', 'that', 'they', 'there', 'other'],
  },

  z_devoicing: {
    tag: 'z_devoicing',
    expected: 'z',
    spoken: 's',
    severity: 'medium',
    category: 'consonant',
    spanishAnchor: "Spanish has no /z/ sound — you default to /s/",
    englishTarget: "English /z/ — same position as /s/ but with vibration",
    bridgeInstruction: "Make an /s/ sound, then turn on your voice. Put your fingers on your throat — you should feel buzzing. Keep the same tongue position.",
    minimalPairs: [['zip', 'sip'], ['zoo', 'sue'], ['buzz', 'bus'], ['eyes', 'ice']],
    commonWords: ['is', 'was', 'has', 'because', 'always', 'easy'],
  },

  sh_as_ch: {
    tag: 'sh_as_ch',
    expected: 'ʃ',
    spoken: 'tʃ',
    severity: 'medium',
    category: 'consonant',
    spanishAnchor: "Spanish 'ch' starts with a /t/ stop that English 'sh' doesn't need",
    englishTarget: "English /sh/ — continuous airflow, no /t/ at the start",
    bridgeInstruction: "Drop the /t/ from your /ch/. Just let air flow over your tongue continuously. Think of hushing someone: 'shhh'.",
    minimalPairs: [['ship', 'chip'], ['share', 'chair'], ['shop', 'chop'], ['wash', 'watch']],
    commonWords: ['she', 'should', 'show', 'sure', 'fish', 'wish'],
  },

  h_velar: {
    tag: 'h_velar',
    expected: 'h',
    spoken: 'x',
    severity: 'low',
    category: 'consonant',
    spanishAnchor: "Spanish /j/ (jota) is produced deep in the throat with friction",
    englishTarget: "English /h/ — just a gentle breath, like fogging a mirror",
    bridgeInstruction: "Relax your throat completely. English /h/ is just a puff of air — no friction, no scratchiness. Pretend you're fogging up a window.",
    minimalPairs: [['hat', 'at'], ['hear', 'ear'], ['hill', 'ill'], ['heat', 'eat']],
    commonWords: ['have', 'he', 'her', 'how', 'here', 'help'],
  },

  unaspirated_ptk: {
    tag: 'unaspirated_ptk',
    expected: 'p',
    spoken: 'p',
    severity: 'low',
    category: 'consonant',
    spanishAnchor: "Spanish /p/, /t/, /k/ have no burst of air",
    englishTarget: "English /p/, /t/, /k/ at the start of a word need a puff of air",
    bridgeInstruction: "Hold your hand in front of your mouth and say 'pot.' You should feel a puff of air on the /p/. In Spanish, that puff doesn't happen — in English, it's expected.",
    minimalPairs: [['pot', 'bot'], ['top', 'stop'], ['cat', 'scat']],
    commonWords: ['people', 'time', 'come', 'take', 'put', 'keep'],
  },

  clear_l_coda: {
    tag: 'clear_l_coda',
    expected: 'ɫ',
    spoken: 'l',
    severity: 'low',
    category: 'consonant',
    spanishAnchor: "Spanish always uses a clear /l/ — tongue tip touches the ridge behind your teeth",
    englishTarget: "English /l/ at the end of words is 'dark' — tongue pulls back",
    bridgeInstruction: "At the end of a word like 'full', let the back of your tongue rise toward the roof of your mouth while the tip stays up. It sounds deeper than Spanish /l/.",
    minimalPairs: [['feel', 'fill'], ['pool', 'pull'], ['tall', 'toll']],
    commonWords: ['all', 'will', 'well', 'still', 'full', 'school'],
  },

  rhotic_trilled: {
    tag: 'rhotic_trilled',
    expected: 'ɹ',
    spoken: 'r',
    severity: 'high',
    category: 'consonant',
    spanishAnchor: "Spanish /r/ uses tongue trill or tap against the ridge",
    englishTarget: "English /r/ — tongue curls back, never touches the roof",
    bridgeInstruction: "Curl your tongue tip slightly back without touching anything in your mouth. Round your lips a tiny bit. Your tongue should float in the middle of your mouth — never tap or trill.",
    minimalPairs: [['red', 'led'], ['right', 'light'], ['rock', 'lock']],
    commonWords: ['really', 'run', 'read', 'right', 'room', 'around'],
  },

  cluster_simplification: {
    tag: 'cluster_simplification',
    expected: '',
    spoken: '',
    severity: 'medium',
    category: 'consonant',
    spanishAnchor: "Spanish avoids complex consonant clusters at the end of words",
    englishTarget: "English requires all consonants in a cluster to be pronounced",
    bridgeInstruction: "Practice saying the final consonant cluster slowly, then speed up. For 'asked', say 'ask' then add the /t/. For 'texts', say 'tex' then add /ts/.",
    minimalPairs: [['asked', 'ask'], ['texts', 'tex'], ['helped', 'help']],
    commonWords: ['asked', 'worked', 'texts', 'helped', 'scripts', 'months'],
  },

  s_epenthesis: {
    tag: 's_epenthesis',
    expected: 's',
    spoken: 'es',
    severity: 'medium',
    category: 'consonant',
    spanishAnchor: "Spanish adds /e/ before s-clusters — 'escuela', 'España'",
    englishTarget: "English starts directly with /s/ — no vowel before it",
    bridgeInstruction: "Start with a hissing /sss/ sound, then attach the rest of the word. Practice: 'sss-top', 'sss-chool', 'sss-pain'. No 'e' at the start.",
    minimalPairs: [['school', 'eschool'], ['Spain', 'eSpain'], ['stop', 'estop']],
    commonWords: ['school', 'start', 'stop', 'speak', 'special', 'study'],
  },

  // ── Vowel substitutions ──────────────────────────────────────

  no_schwa_reduction: {
    tag: 'no_schwa_reduction',
    expected: 'ə',
    spoken: 'a',
    severity: 'medium',
    category: 'vowel',
    spanishAnchor: "Spanish pronounces every vowel clearly — no 'lazy' vowels",
    englishTarget: "English unstressed syllables use schwa /ə/ — a short, neutral sound",
    bridgeInstruction: "In unstressed syllables, let the vowel become lazy and short — almost like a tiny 'uh'. Don't give it full value. The word 'banana' has TWO schwas: buh-NA-nuh.",
    minimalPairs: [['about', 'a-bout'], ['banana', 'ba-na-na']],
    commonWords: ['about', 'the', 'another', 'problem', 'system', 'support'],
  },

  vowel_collapse: {
    tag: 'vowel_collapse',
    expected: 'æ',
    spoken: 'a',
    severity: 'medium',
    category: 'vowel',
    spanishAnchor: "Spanish has only 5 vowels — English has ~15",
    englishTarget: "English distinguishes vowels that Spanish merges into one /a/",
    bridgeInstruction: "English /æ/ (cat) and /ʌ/ (cup) are different sounds. For /æ/, spread your lips wide and lower your jaw. For /ʌ/, relax your mouth to a neutral position.",
    minimalPairs: [['cat', 'cut'], ['bat', 'but'], ['cap', 'cup'], ['hat', 'hut']],
    commonWords: ['cat', 'had', 'man', 'back', 'that', 'can'],
  },

  i_vs_ee_merge: {
    tag: 'i_vs_ee_merge',
    expected: 'ɪ',
    spoken: 'i',
    severity: 'medium',
    category: 'vowel',
    spanishAnchor: "Spanish has one /i/ sound — English has two (/ɪ/ and /iː/)",
    englishTarget: "Short /ɪ/ (bit) is more relaxed than long /iː/ (beat)",
    bridgeInstruction: "For short /ɪ/ (as in 'bit'), relax your tongue and jaw — don't smile as much. It's shorter and lazier than the Spanish /i/. For long /iː/ (as in 'beat'), that's closer to your Spanish /i/.",
    minimalPairs: [['bit', 'beat'], ['sit', 'seat'], ['ship', 'sheep'], ['fill', 'feel']],
    commonWords: ['it', 'is', 'this', 'with', 'big', 'did'],
  },

  ae_substitution: {
    tag: 'ae_substitution',
    expected: 'æ',
    spoken: 'e',
    severity: 'medium',
    category: 'vowel',
    spanishAnchor: "Spanish /e/ is close but too closed for English /æ/",
    englishTarget: "English /æ/ requires your jaw to drop lower than for /e/",
    bridgeInstruction: "Open your mouth wider than for Spanish /e/. Drop your jaw and spread your lips. It should feel exaggerated at first. 'Cat' should sound distinctly different from 'ket'.",
    minimalPairs: [['cat', 'ket'], ['bad', 'bed'], ['man', 'men'], ['had', 'head']],
    commonWords: ['cat', 'bad', 'man', 'had', 'back', 'have'],
  },

  cup_as_cap: {
    tag: 'cup_as_cap',
    expected: 'ʌ',
    spoken: 'a',
    severity: 'medium',
    category: 'vowel',
    spanishAnchor: "You're using Spanish /a/ which is too open for English /ʌ/",
    englishTarget: "English /ʌ/ (cup) — a short, neutral sound in the center of your mouth",
    bridgeInstruction: "Relax your mouth to a neutral position — not wide open like for /a/. The sound is short and central, almost like a quick grunt. Think of the 'u' in 'up' as a very short, lazy sound.",
    minimalPairs: [['cup', 'cap'], ['luck', 'lack'], ['bud', 'bad'], ['run', 'ran']],
    commonWords: ['up', 'but', 'just', 'much', 'come', 'some'],
  },

  u_merge: {
    tag: 'u_merge',
    expected: 'ʊ',
    spoken: 'u',
    severity: 'low',
    category: 'vowel',
    spanishAnchor: "Spanish has one /u/ sound — English has two (/ʊ/ and /uː/)",
    englishTarget: "Short /ʊ/ (book) is relaxed, long /uː/ (boot) is tense",
    bridgeInstruction: "For short /ʊ/ (as in 'book'), keep your lips only slightly rounded and the sound short. Don't purse your lips as much as for Spanish /u/. For long /uː/ (as in 'boot'), that's closer to your Spanish /u/.",
    minimalPairs: [['full', 'fool'], ['pull', 'pool'], ['look', 'Luke'], ['would', 'wooed']],
    commonWords: ['good', 'book', 'look', 'could', 'put', 'would'],
  },

  monophthongised_diphthong: {
    tag: 'monophthongised_diphthong',
    expected: 'aɪ',
    spoken: 'a',
    severity: 'medium',
    category: 'vowel',
    spanishAnchor: "Spanish diphthongs are shorter and less gliding than English ones",
    englishTarget: "English diphthongs need a clear glide from one vowel to another",
    bridgeInstruction: "Exaggerate the glide. For 'time' (aɪ), start with mouth open on /a/ then move to a smile for /ɪ/. For 'go' (oʊ), start with an open 'o' then round your lips. You should feel your mouth moving during the vowel.",
    minimalPairs: [['time', 'tam'], ['go', 'gah'], ['say', 'seh'], ['now', 'nah']],
    commonWords: ['time', 'like', 'make', 'go', 'know', 'how'],
  },

  // ── Prosody ──────────────────────────────────────────────────

  syllable_timed: {
    tag: 'syllable_timed',
    expected: '',
    spoken: '',
    severity: 'high',
    category: 'prosody',
    spanishAnchor: "Spanish gives equal time to each syllable — ta-ta-ta-ta",
    englishTarget: "English is stress-timed — stressed syllables are longer, unstressed are shorter",
    bridgeInstruction: "Exaggerate the contrast: make stressed syllables LONG and loud, unstressed syllables quick and quiet. In 'baNAna', the 'NA' should be noticeably louder and longer than 'ba' and 'na'.",
    minimalPairs: [['record (noun)', 'record (verb)'], ['present (noun)', 'present (verb)']],
    commonWords: ['important', 'banana', 'computer', 'together', 'information'],
  },

  wrong_stress: {
    tag: 'wrong_stress',
    expected: '',
    spoken: '',
    severity: 'medium',
    category: 'prosody',
    spanishAnchor: "Spanish stress rules are regular — English stress is unpredictable",
    englishTarget: "Each English word has a fixed stress pattern that must be memorized",
    bridgeInstruction: "When learning a new word, always learn which syllable is stressed. Say it with exaggerated stress at first. Dictionaries mark stress with an apostrophe before the stressed syllable.",
    minimalPairs: [['PREsent (noun)', 'preSENT (verb)'], ['REcord (noun)', 'reCORD (verb)']],
    commonWords: ['development', 'information', 'important', 'education'],
  },

  question_intonation: {
    tag: 'question_intonation',
    expected: '',
    spoken: '',
    severity: 'low',
    category: 'prosody',
    spanishAnchor: "Spanish yes/no questions rise; English sometimes falls on wh-questions",
    englishTarget: "English wh-questions fall at the end; yes/no questions rise",
    bridgeInstruction: "For yes/no questions ('Are you coming?'), let your voice rise at the end. For wh-questions ('Where are you going?'), let it fall. Practice by humming the melody without words.",
    minimalPairs: [['You like it. (statement)', 'You like it? (question)']],
    commonWords: ['where', 'what', 'when', 'how', 'do you', 'are you'],
  },
} as const satisfies Readonly<Record<L1Tag, BridgeRule>>;
