// Deterministic Bogotá-Spanish calque checklist for L1 transfer detection
import type { CalqueEntry } from './calqueList.types';

// Word-boundary helper: builds a case-insensitive regex matching the phrase at word boundaries
function wb(phrase: string): RegExp {
  const escaped = phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`\\b${escaped}\\b`, 'i');
}

const FALSE_FRIENDS: CalqueEntry[] = [
  {
    trigger: 'actually',
    pattern: /\bactually\b(?=\s+(?:i|we|they|he|she|it|the|my|our)\b)/i,
    l1Source: 'actualmente',
    correction: 'currently, nowadays',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "actualmente" means "currently", not "actually" (= en realidad).',
  },
  {
    trigger: 'assist to',
    pattern: wb('assist to'),
    l1Source: 'asistir a',
    correction: 'attend',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "asistir" means "attend"; English "assist" means "help".',
  },
  {
    trigger: 'realize',
    pattern: /\brealize[ds]?\s+(?:the|a|an|this|that|my|our|some)\b/i,
    l1Source: 'realizar',
    correction: 'carry out, accomplish',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "realizar" means "carry out"; English "realize" means "become aware".',
  },
  {
    trigger: 'sensible',
    pattern: /\bsensible\b/i,
    l1Source: 'sensible',
    correction: 'sensitive',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "sensible" means "sensitive"; English "sensible" means "reasonable".',
  },
  {
    trigger: 'support',
    pattern: /\b(?:can(?:'?t)?|cannot|don'?t)\s+support\b/i,
    l1Source: 'soportar',
    correction: 'tolerate, put up with, stand',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "soportar" means "tolerate"; English "support" means "back/uphold".',
  },
  {
    trigger: 'discuss',
    pattern: /\bdiscuss(?:ed|ing)?\s+with\b/i,
    l1Source: 'discutir con',
    correction: 'argue with',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "discutir" often means "argue"; English "discuss" is more neutral.',
  },
  {
    trigger: 'molest',
    pattern: /\bmolest(?:s|ed|ing)?\b/i,
    l1Source: 'molestar',
    correction: 'bother, annoy',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "molestar" means "bother"; English "molest" has a much stronger meaning.',
  },
  {
    trigger: 'career',
    pattern: /\b(?:study|studying|finish|my)\s+(?:a\s+)?career\b/i,
    l1Source: 'carrera',
    correction: 'degree, major',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "carrera" can mean "degree/major"; English "career" means "profession".',
  },
  {
    trigger: 'compromise',
    pattern: /\b(?:a|the|my|our)\s+compromise\b/i,
    l1Source: 'compromiso',
    correction: 'commitment, obligation',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "compromiso" means "commitment"; English "compromise" means "concession".',
  },
  {
    trigger: 'introduce',
    pattern: /\bintroduce[ds]?\s+(?:the|a|it|them|this)\s+(?:in|into|inside)\b/i,
    l1Source: 'introducir',
    correction: 'insert, put in',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "introducir" means "insert"; English "introduce" means "present".',
  },
  {
    trigger: 'educated',
    pattern: /\b(?:very|so|really|quite|well)\s+educated\b/i,
    l1Source: 'educado',
    correction: 'polite, well-mannered',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "educado" means "polite"; English "educated" means "learned".',
  },
  {
    trigger: 'carpet',
    pattern: /\bcarpet\b/i,
    l1Source: 'carpeta',
    correction: 'folder',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "carpeta" means "folder"; English "carpet" means "floor covering".',
  },
  {
    trigger: 'library',
    pattern: /\b(?:buy|bought|purchase|from\s+the)\s+library\b/i,
    l1Source: 'librería',
    correction: 'bookstore',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "librería" means "bookstore"; English "library" is for borrowing books.',
  },
  {
    trigger: 'embarrassed',
    pattern: /\b(?:she|he)\s+(?:is|was)\s+embarrassed\b/i,
    l1Source: 'embarazada',
    correction: 'pregnant',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "embarazada" means "pregnant"; confirm intended meaning from context.',
  },
  {
    trigger: 'constipated',
    pattern: /\bconstipated\b/i,
    l1Source: 'constipado',
    correction: 'have a cold',
    flagType: 'false_friend',
    dimension: 'false_friend',
    rationale: 'Spanish "constipado" means "have a cold"; English "constipated" is a digestive issue.',
  },
];

const CALQUED_COLLOCATIONS: CalqueEntry[] = [
  {
    trigger: 'make a party',
    pattern: wb('make a party'),
    l1Source: 'hacer una fiesta',
    correction: 'throw a party, have a party',
    flagType: 'calqued_collocation',
    dimension: 'collocation',
    rationale: 'Direct translation from "hacer una fiesta"; native speakers "throw" or "have" a party.',
  },
  {
    trigger: 'make a question',
    pattern: wb('make a question'),
    l1Source: 'hacer una pregunta',
    correction: 'ask a question',
    flagType: 'calqued_collocation',
    dimension: 'collocation',
    rationale: 'Direct translation from "hacer una pregunta"; native speakers "ask" a question.',
  },
  {
    trigger: 'make a photo',
    pattern: wb('make a photo'),
    l1Source: 'hacer una foto',
    correction: 'take a photo',
    flagType: 'calqued_collocation',
    dimension: 'collocation',
    rationale: 'Direct translation from "hacer una foto"; native speakers "take" a photo.',
  },
  {
    trigger: 'take a decision',
    pattern: wb('take a decision'),
    l1Source: 'tomar una decisión',
    correction: 'make a decision',
    flagType: 'calqued_collocation',
    dimension: 'collocation',
    rationale: 'Direct translation from "tomar una decisión"; native speakers "make" a decision.',
  },
  {
    trigger: 'have reason',
    pattern: /\b(?:you|they|we|he|she|i)\s+have\s+reason\b/i,
    l1Source: 'tener razón',
    correction: 'be right',
    flagType: 'calqued_collocation',
    dimension: 'collocation',
    rationale: 'Direct translation from "tener razón"; native speakers say "be right".',
  },
  {
    trigger: 'put attention',
    pattern: wb('put attention'),
    l1Source: 'poner atención',
    correction: 'pay attention',
    flagType: 'calqued_collocation',
    dimension: 'collocation',
    rationale: 'Direct translation from "poner atención"; native speakers "pay" attention.',
  },
  {
    trigger: 'do a mistake',
    pattern: wb('do a mistake'),
    l1Source: 'hacer un error',
    correction: 'make a mistake',
    flagType: 'calqued_collocation',
    dimension: 'collocation',
    rationale: 'Direct translation from "hacer un error"; native speakers "make" a mistake.',
  },
];

const CALQUED_SYNTAX: CalqueEntry[] = [
  {
    trigger: 'i have',
    pattern: /\bi\s+have\s+\d+\s+years?\b/i,
    l1Source: 'tengo X años',
    correction: "I'm X years old",
    flagType: 'calqued_syntax',
    dimension: 'syntax',
    rationale: 'Direct translation from "tengo X años"; English uses "be" + age + "years old".',
  },
  {
    trigger: 'i am agree',
    pattern: /\bi\s+am\s+agree\b/i,
    l1Source: 'estoy de acuerdo',
    correction: 'I agree',
    flagType: 'calqued_syntax',
    dimension: 'syntax',
    rationale: 'Direct translation from "estoy de acuerdo"; English uses "agree" as a verb, not "be agree".',
  },
  {
    trigger: 'the majority of',
    pattern: /\bthe\s+majority\s+of\s+\w+\s+(?:thinks|believes|wants|feels|says)\b/i,
    l1Source: 'la mayoría piensa',
    correction: 'The majority of... think/believe/want',
    flagType: 'calqued_syntax',
    dimension: 'syntax',
    rationale: '"The majority of + plural noun" takes a plural verb in English.',
  },
  {
    trigger: 'how is it called',
    pattern: /\bhow\s+is\s+(?:it|this|that)\s+called\b/i,
    l1Source: 'cómo se llama',
    correction: 'What is it called?',
    flagType: 'calqued_syntax',
    dimension: 'syntax',
    rationale: 'Direct translation from "cómo se llama"; English uses "what", not "how".',
  },
  {
    trigger: 'depends of',
    pattern: wb('depends of'),
    l1Source: 'depende de',
    correction: 'depends on',
    flagType: 'calqued_syntax',
    dimension: 'syntax',
    rationale: 'Spanish "depende de" → English "depends on", not "depends of".',
  },
  {
    trigger: 'the people is',
    pattern: /\bthe\s+people\s+is\b/i,
    l1Source: 'la gente es',
    correction: 'people are',
    flagType: 'calqued_syntax',
    dimension: 'syntax',
    rationale: '"People" is plural in English; "la gente" is singular in Spanish.',
  },
  {
    trigger: 'i am here since',
    pattern: /\bi\s+(?:am|live|work)\s+(?:here|there)\s+since\b/i,
    l1Source: 'estoy aquí desde',
    correction: 'I have been here since',
    flagType: 'calqued_syntax',
    dimension: 'syntax',
    rationale: 'Spanish uses present tense with "desde"; English requires present perfect.',
  },
  {
    trigger: 'double negative',
    pattern: /\b(?:don'?t|doesn'?t|didn'?t|can'?t|won'?t)\s+\w+\s+no(?:thing|body|where|one)\b/i,
    l1Source: 'no...nada/nadie',
    correction: 'Use single negation: "don\'t...anything" or "nothing"',
    flagType: 'calqued_syntax',
    dimension: 'syntax',
    rationale: 'Spanish uses double negatives ("no hay nada"); English uses single negation.',
  },
];

/** All 30 deterministic calque entries combined. */
export const CALQUE_LIST: CalqueEntry[] = [
  ...FALSE_FRIENDS,
  ...CALQUED_COLLOCATIONS,
  ...CALQUED_SYNTAX,
];
